### ISSUE TITLE
Hi, I want to add some words to text-phone from CMU dict and  librispeech-lexicon, but they are different with speechocen762

### ISSUE THREAD

**Issue by YangangCao** [YuanGongND/gopt#28]
Hi, dear author, I want to infer some my own data, but some words don't exist in speechocean762/resource/lexicon.txt or speechocean762/resource/text-phone, so I want to add them. But I found a problem.

For example:

In speechocean762/recource/text-phone:
000010011.0 W_B IY0_E

In speechocean762/recource/lexicon.txt:
WE W IY0

However, in every version [CMU dict:](https://github.com/Alexir/CMUdict)
WE W IY1

In   [librispeech-lexicon.txt](http://www.openslr.org/11/)
WE  W IY1

[CMU website](http://www.speech.cs.cmu.edu/cgi-bin/cmudict) said 0 and 1 represent different lexical stress:
0    — No stress
1    — Primary stress
2    — Secondary stress

lots of difference stresses appear between speechocean762 and other dict, which one is true?

**Comment by YangangCao** [comment]
@LyWangPX

**Comment by YuanGongND** [comment]
hi there,

I think this should be a question to https://github.com/kaldi-asr/kaldi/issues?q=is%3Aissue+gop. 

I closely follow the original GOP recipe and get the GOP features, which are also released. We do not propose anything new in GOP feature generation and you should be able to reproduce that by using a late 2021 commit of Kaldi GOP recipe and SO762 dataset.

-Yuan
